# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fuse < Formula
  desc "The ultimate AI assistant for Platform Engineers, crafted by the Botkube Team."
  homepage "https://botkube.io/fuse"
  version "0.6.0"

  on_macos do
    on_intel do
      url "https://github.com/kubeshop/fuse-releases/releases/download/v0.6.0/fuse-darwin-amd64"
      sha256 "add6afab4ae0b14a43c32e6d4cc7b6fa038791d75ecbd2caf571f11f4d213442"

      def install
        bin.install "fuse-darwin-amd64" => "fuse"
      end
    end
    on_arm do
      url "https://github.com/kubeshop/fuse-releases/releases/download/v0.6.0/fuse-darwin-arm64"
      sha256 "147778f9879c6e70049326bdac2ca350c745c41a424f4dcb941d57f0292dc817"

      def install
        bin.install "fuse-darwin-arm64" => "fuse"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kubeshop/fuse-releases/releases/download/v0.6.0/fuse-linux-amd64"
        sha256 "022bc826b7a223816fd03080ba459d098d6517668833b20bfd53de3c5836355f"

        def install
          bin.install "fuse-linux-amd64" => "fuse"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kubeshop/fuse-releases/releases/download/v0.6.0/fuse-linux-arm64"
        sha256 "d4d972200ea0ba6eba5a80907f49780f0344ed02ec4888ff90d5860def125595"

        def install
          bin.install "fuse-linux-arm64" => "fuse"
        end
      end
    end
  end

  test do
    system "#{bin}/fuse version"
  end
end
